<a href="https://colab.research.google.com/github/Swaraj-sj2000/Machine-leaning-projects/blob/main/KNN_CLASSIFIER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def euclidean_distance(arr1,arr2):
  try:
    if arr1.shape !=arr2.shape:
      raise ValueError("mismatched shape")
    if not isinstance(arr1, np.ndarray):
      arr1 = np.array(arr1)
    if not isinstance(arr2, np.ndarray):
      arr2 = np.array(arr2)

    return np.sqrt(np.sum((arr1-arr2)**2))
  except Exception as e:
    print(e)

In [ ]:
def manhatten_distance(arr1,arr2):
  try:
    if arr1.shape !=arr2.shape:
      raise ValueError("mismatched shape")
    if not isinstance(arr1, np.ndarray):
      arr1 = np.array(arr1)
    if not isinstance(arr2, np.ndarray):
      arr2 = np.array(arr2)

    return np.sum(np.abs(arr1-arr2))
  except Exception as e:
    print(e)

In [ ]:
import numpy as np
import statistics as sts

In [56]:
class KNN_Classifier:
  def __init__(self,distance_metric=0):
    self.distance_metric=distance_metric


  def get_distance_metric(self,training_data_point,test_data_point):
    if self.distance_metric==0: #euclidean
      dist=0
      for i in range(len(training_data_point)-1): #we only take features of training data into account
        dist=dist+(training_data_point[i]-test_data_point[i])**2
      euclidean_dist=np.sqrt(dist)
      return euclidean_dist

    elif self.distance_metric==1: #manhatten
      dist=0
      for i in range(len(training_data_point)-1):
        dist=dist+abs(training_data_point[i]-test_data_point[i])
      manhatten_dist=dist
      return manhatten_dist

  def nearest_neighbours(self,X_train,test_data,k): #training data contains both features and target but testing data contains only features

    distance_list=[]
    for training_data in X_train:
      distance=self.get_distance_metric(training_data,test_data)
      distance_list.append((training_data,distance))  #appending each data point and their distance from the test point

    distance_list.sort(key=lambda x:x[1])  #sorting each data point with the increasing order of distances from the test point
    neighbours_list=[]

    for j in range(k):                      #taking first k neighbours
      neighbours_list.append(distance_list[j][0])

    return neighbours_list

  def predict(self,X_train,test_data,k):
    neighbours=self.nearest_neighbours(X_train,test_data,k)
    label=[]
    for data in neighbours:

      label.append(data[-1])

    predicted_class=sts.mode(label)
    return predicted_class





In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [ ]:
diab_df=pd.read_csv("/content/diabetes.csv")
diab_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
X=diab_df.iloc[:,:-1]
Y=diab_df.iloc[:,-1]

In [ ]:
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [ ]:
Y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [ ]:
X.shape

(768, 8)

In [ ]:
X=X.to_numpy()
Y=Y.to_numpy()
print(X)
print(Y)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=42)

In [ ]:
#training data here contains both feature and label
X_train=np.insert(X_train,8,Y_train,axis=1)
print(X_train)

[[1.00e+00 9.00e+01 6.20e+01 ... 5.80e-01 2.40e+01 0.00e+00]
 [5.00e+00 1.26e+02 7.80e+01 ... 4.39e-01 4.00e+01 0.00e+00]
 [2.00e+00 1.05e+02 5.80e+01 ... 2.25e-01 2.50e+01 0.00e+00]
 ...
 [1.00e+00 9.70e+01 7.00e+01 ... 2.18e-01 3.00e+01 0.00e+00]
 [1.00e+01 1.11e+02 7.00e+01 ... 1.41e-01 4.00e+01 1.00e+00]
 [4.00e+00 1.44e+02 5.80e+01 ... 2.87e-01 3.70e+01 0.00e+00]]


In [ ]:
X_train.shape

(614, 9)

In [ ]:
print(X_train[:,8])

[0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1.
 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 0.
 0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1.
 1. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.
 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1.
 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0.
 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1.
 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1.
 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 1.
 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.

In [ ]:
knn=KNN_Classifier(distance_metric=1)

In [ ]:
pred=knn.predict(X_train,X_test[2],k=5)

In [ ]:
print(X_test[2])

[  2.    122.     76.     27.    200.     35.9     0.483  26.   ]


In [ ]:
print(Y_test[2])

0


In [ ]:
print(pred)

0.0


In [ ]:
prediction=[]
for i in range(X_test.shape[0]):
  prediction.append(knn.predict(X_train,X_test[i],k=5))

In [ ]:
print(prediction)

[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0]


In [ ]:
acc_sc=accuracy_score(Y_test,prediction)
print(acc_sc)

0.7272727272727273
